services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/api-gateway/.env
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
      ecommerce-service:
        condition: service_started

  ecommerce-service:
    build:
      context: ./backend/ecommerce-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/ecommerce-service/.env
    depends_on:
      db:
        condition: service_healthy

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
